# https://docs.pypi.org/trusted-publishers/using-a-publisher/
name: PyPI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install rye
        uses: eifinger/setup-rye@v1.10.0
      - name: Install dependencies
        run: |
          rye sync
      - name: Build
        run: |
          rye build --all
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
