# https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: PyPI

on: push

jobs:
  deploy:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          rye sync
      - name: Build
        run: |
          rye build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
